"""Build binary student artifacts (docx, pptx) and LaTeX sources.

Reads one JSON object from stdin and writes artifact files under output_dir.
Returns a JSON object with previewPath, downloadPath, and mimeType on stdout.
"""
from __future__ import annotations

import json
import re
import sys
import zipfile
from pathlib import Path
from xml.sax.saxutils import escape


def slugify(value: str) -> str:
    text = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return (text or "artifact")[:48]


def write_preview_html(path: Path, title: str, body: str, extra_head: str = "") -> None:
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{escape(title)}</title>
  <style>
    body {{
      font-family: "Segoe UI", system-ui, sans-serif;
      margin: 0;
      padding: 24px;
      background: #f7f8fc;
      color: #1b2138;
      line-height: 1.5;
    }}
    .shell {{
      max-width: 900px;
      margin: 0 auto;
      background: #fff;
      border: 1px solid #d8deef;
      border-radius: 14px;
      padding: 24px;
    }}
    h1, h2, h3 {{ margin-top: 0; }}
    ul {{ padding-left: 1.2rem; }}
    pre {{
      white-space: pre-wrap;
      background: rgba(127, 136, 180, 0.08);
      border: 1px solid #d8deef;
      border-radius: 10px;
      padding: 16px;
    }}
  </style>
  {extra_head}
</head>
<body>
  <div class="shell">
    {body}
  </div>
</body>
</html>"""
    path.write_text(html, encoding="utf-8")


def paragraph_xml(text: str) -> str:
    return (
        "<w:p>"
        "<w:r>"
        f"<w:t>{escape(text)}</w:t>"
        "</w:r>"
        "</w:p>"
    )


def heading_xml(text: str, level: int = 1) -> str:
    style = "Heading1" if level <= 1 else "Heading2"
    return (
        "<w:p>"
        "<w:pPr>"
        f"<w:pStyle w:val=\"{style}\"/>"
        "</w:pPr>"
        "<w:r>"
        f"<w:t>{escape(text)}</w:t>"
        "</w:r>"
        "</w:p>"
    )


def build_docx(output_dir: Path, title: str, content: dict) -> dict:
    sections = content.get("sections") or []
    if not sections and content.get("paragraphs"):
        sections = [{"paragraphs": content.get("paragraphs") or []}]
    if not sections and content.get("body"):
        sections = [{"paragraphs": [str(content.get("body"))]}]

    body_parts = []
    for section in sections:
        heading = section.get("heading") or section.get("title")
        if heading:
            body_parts.append(heading_xml(str(heading), section.get("level", 1)))
        for paragraph in section.get("paragraphs") or []:
            body_parts.append(paragraph_xml(str(paragraph)))
        for bullet in section.get("bullets") or []:
            body_parts.append(paragraph_xml(f"• {bullet}"))

    if not body_parts:
        body_parts.append(paragraph_xml("Generated by Nucleus."))

    document_xml = (
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>"
        "<w:document xmlns:w=\"http://schemas.openxmlformats.org/wordprocessingml/2006/main\">"
        "<w:body>"
        + "".join(body_parts)
        + "<w:sectPr/></w:body></w:document>"
    )
    content_types = (
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>"
        "<Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\">"
        "<Default Extension=\"rels\" ContentType=\"application/vnd.openxmlformats-package.relationships+xml\"/>"
        "<Default Extension=\"xml\" ContentType=\"application/xml\"/>"
        "<Override PartName=\"/word/document.xml\" "
        "ContentType=\"application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml\"/>"
        "</Types>"
    )
    rels = (
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>"
        "<Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\">"
        "<Relationship Id=\"rId1\" "
        "Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument\" "
        "Target=\"word/document.xml\"/>"
        "</Relationships>"
    )

    filename = f"{slugify(title)}.docx"
    docx_path = output_dir / filename
    with zipfile.ZipFile(docx_path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("[Content_Types].xml", content_types)
        archive.writestr("_rels/.rels", rels)
        archive.writestr("word/document.xml", document_xml)

    preview_sections = []
    for section in sections:
        heading = section.get("heading") or section.get("title")
        if heading:
            preview_sections.append(f"<h2>{escape(str(heading))}</h2>")
        bullets = section.get("bullets") or []
        if bullets:
            preview_sections.append("<ul>" + "".join(f"<li>{escape(str(item))}</li>" for item in bullets) + "</ul>")
        for paragraph in section.get("paragraphs") or []:
            preview_sections.append(f"<p>{escape(str(paragraph))}</p>")
    preview_path = output_dir / f"{slugify(title)}.preview.html"
    write_preview_html(preview_path, title, f"<h1>{escape(title)}</h1>{''.join(preview_sections)}")

    return {
        "previewPath": preview_path.name,
        "downloadPath": docx_path.name,
        "mimeType": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    }


def slide_xml(title: str, bullets: list[str]) -> str:
    bullet_xml = "".join(
        "<a:p>"
        "<a:pPr lvl=\"0\"/>"
        "<a:r><a:t>" + escape(str(item)) + "</a:t></a:r>"
        "</a:p>"
        for item in bullets
    )
    return (
        "<p:sld xmlns:a=\"http://schemas.openxmlformats.org/drawingml/2006/main\" "
        "xmlns:p=\"http://schemas.openxmlformats.org/presentationml/2006/main\" "
        "xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\">"
        "<p:cSld>"
        "<p:spTree>"
        "<p:nvGrpSpPr><p:cNvPr id=\"1\" name=\"\"/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr>"
        "<p:grpSpPr/>"
        "<p:sp>"
        "<p:nvSpPr><p:cNvPr id=\"2\" name=\"Title\"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr>"
        "<p:spPr/><p:txBody><a:bodyPr/><a:lstStyle/>"
        "<a:p><a:r><a:t>" + escape(title) + "</a:t></a:r></a:p>"
        "</p:txBody></p:sp>"
        "<p:sp>"
        "<p:nvSpPr><p:cNvPr id=\"3\" name=\"Content\"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr>"
        "<p:spPr/><p:txBody><a:bodyPr/><a:lstStyle/>"
        + bullet_xml
        + "</p:txBody></p:sp>"
        "</p:spTree>"
        "</p:cSld>"
        "</p:sld>"
    )


def build_pptx(output_dir: Path, title: str, content: dict) -> dict:
    slides = content.get("slides") or []
    if not slides:
        slides = [{"title": title, "bullets": content.get("bullets") or ["Generated by Nucleus."]}]

    slide_parts = []
    slide_rels = []
    for index, slide in enumerate(slides, start=1):
        slide_name = f"ppt/slides/slide{index}.xml"
        slide_parts.append((slide_name, slide_xml(str(slide.get("title") or f"Slide {index}"), slide.get("bullets") or [])))
        slide_rels.append(
            "<Relationship Id=\"rId" + str(index) + "\" "
            "Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide\" "
            "Target=\"slides/slide" + str(index) + ".xml\"/>"
        )

    presentation_xml = (
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>"
        "<p:presentation xmlns:a=\"http://schemas.openxmlformats.org/drawingml/2006/main\" "
        "xmlns:p=\"http://schemas.openxmlformats.org/presentationml/2006/main\" "
        "xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\">"
        "<p:sldIdLst>"
        + "".join(f"<p:sldId id=\"{256 + i}\" r:id=\"rId{i}\"/>" for i in range(1, len(slides) + 1))
        + "</p:sldIdLst></p:presentation>"
    )
    presentation_rels = (
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>"
        "<Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\">"
        + "".join(slide_rels)
        + "</Relationships>"
    )
    content_types = (
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>"
        "<Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\">"
        "<Default Extension=\"rels\" ContentType=\"application/vnd.openxmlformats-package.relationships+xml\"/>"
        "<Default Extension=\"xml\" ContentType=\"application/xml\"/>"
        "<Override PartName=\"/ppt/presentation.xml\" "
        "ContentType=\"application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml\"/>"
        + "".join(
            f"<Override PartName=\"/ppt/slides/slide{i}.xml\" "
            "ContentType=\"application/vnd.openxmlformats-officedocument.presentationml.slide+xml\"/>"
            for i in range(1, len(slides) + 1)
        )
        + "</Types>"
    )
    package_rels = (
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>"
        "<Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\">"
        "<Relationship Id=\"rId1\" "
        "Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument\" "
        "Target=\"ppt/presentation.xml\"/>"
        "</Relationships>"
    )

    filename = f"{slugify(title)}.pptx"
    pptx_path = output_dir / filename
    with zipfile.ZipFile(pptx_path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("[Content_Types].xml", content_types)
        archive.writestr("_rels/.rels", package_rels)
        archive.writestr("ppt/presentation.xml", presentation_xml)
        archive.writestr("ppt/_rels/presentation.xml.rels", presentation_rels)
        for slide_name, slide_xml_text in slide_parts:
            archive.writestr(slide_name, slide_xml_text)

    preview_slides = []
    for slide in slides:
        bullets = slide.get("bullets") or []
        preview_slides.append(
            "<section style=\"margin-bottom:18px;padding-bottom:18px;border-bottom:1px solid #d8deef;\">"
            f"<h2>{escape(str(slide.get('title') or 'Slide'))}</h2>"
            + ("<ul>" + "".join(f"<li>{escape(str(item))}</li>" for item in bullets) + "</ul>" if bullets else "")
            + "</section>"
        )
    preview_path = output_dir / f"{slugify(title)}.preview.html"
    write_preview_html(preview_path, title, f"<h1>{escape(title)}</h1>{''.join(preview_slides)}")

    return {
        "previewPath": preview_path.name,
        "downloadPath": pptx_path.name,
        "mimeType": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    }


def build_latex(output_dir: Path, title: str, content: dict) -> dict:
    source = str(content.get("source") or content.get("latex") or "").strip()
    if not source:
        source = (
            "\\documentclass{article}\n"
            "\\usepackage{amsmath}\n"
            "\\begin{document}\n"
            f"\\title{{{title}}}\n"
            "\\maketitle\n"
            "Generated by Nucleus.\n"
            "\\end{document}\n"
        )
    tex_path = output_dir / f"{slugify(title)}.tex"
    tex_path.write_text(source, encoding="utf-8")
    preview_path = output_dir / f"{slugify(title)}.preview.html"
    write_preview_html(
        preview_path,
        title,
        f"<h1>{escape(title)}</h1><pre>{escape(source)}</pre>",
        extra_head=(
            '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css">'
            '<script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.js"></script>'
            '<script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/contrib/auto-render.min.js"></script>'
            "<script>document.addEventListener('DOMContentLoaded',()=>{"
            "window.renderMathInElement&&window.renderMathInElement(document.body,{"
            "delimiters:[{left:'$$',right:'$$',display:true},{left:'$',right:'$',display:false}]"
            "});});</script>"
        ),
    )
    return {
        "previewPath": preview_path.name,
        "downloadPath": tex_path.name,
        "mimeType": "application/x-tex",
    }


def build(payload: dict) -> dict:
    artifact_type = payload.get("type")
    title = payload.get("title") or "Untitled artifact"
    output_dir = Path(payload.get("output_dir") or ".")
    content = payload.get("content") or {}
    output_dir.mkdir(parents=True, exist_ok=True)

    if artifact_type == "docx":
        return build_docx(output_dir, title, content)
    if artifact_type == "pptx":
        return build_pptx(output_dir, title, content)
    if artifact_type == "latex":
        return build_latex(output_dir, title, content)
    raise ValueError(f"Unsupported artifact type: {artifact_type}")


def main() -> int:
    raw = sys.stdin.read()
    payload = json.loads(raw or "{}")
    result = build(payload)
    print(json.dumps(result), flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
