"""Canvas vector retrieval service.

Functionality: loads canvas_graph.json, ranks graph nodes with embedding and
keyword/fuzzy scores, expands graph neighbors for agent/browser context, and
prints newline-delimited JSON responses for main.js.
Dependencies: parser.py node classes, OpenAI embeddings, numpy, and local graph
storage generated by parser.py.
"""
import numpy as np
import json
import heapq
import re
import os
import sys
from difflib import SequenceMatcher
from html import unescape
from pathlib import Path
from dotenv import load_dotenv
from parser import (
    assignmentNode,
    conceptNode,
    course_scoped_embedding_name,
    detailNode,
    eventNode,
    exampleNode,
    fileNode,
    learningBlock,
    problemNode,
    syllabusNode,
)
from openai import OpenAI

load_dotenv()
openai_client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

BASE_DIR = Path(__file__).resolve().parent
CANVAS_GRAPH_PATH = BASE_DIR / "canvas_graph.json"
CANVAS_DATA_PATH = BASE_DIR / "canvas_data.json"

QUERY_PREFIXES = [
    "what is",
    "what are",
    "who is",
    "who are",
    "explain",
    "define",
    "find",
    "search for",
    "tell me about",
    "give me",
    "summarize",
    "describe",
    "how does",
    "how do",
    "why does",
    "why do",
    "show me",
    "where is",
    "when is",
]

INTENT_CONTEXT = {
    "deadline": "deadline due date schedule syllabus assignment event",
    "exam": "exam quiz final midterm review concepts dependencies covered material",
    "assignment": "assignment homework problem set pset due description submission",
    "practice": "practice problem example solution concept worked exercise",
    "concept": "definition explanation concept detail example lecture notes",
    "syllabus": "syllabus course policy grading schedule class information office hours",
    "material": "lecture slides notes pdf reading handout audio recording study material file",
    "general": "course concept assignment event file syllabus lecture material",
}

INTENT_KEYWORDS = {
    "deadline": ["due", "deadline", "when", "date", "schedule"],
    "exam": ["exam", "midterm", "final", "quiz", "test", "review"],
    "syllabus": ["syllabus", "policy", "grading", "grade", "participation", "office hours", "office hour"],
    "assignment": ["assignment", "homework", "problem set", "pset", "submit", "submission", "pset", "solutions"],
    "practice": ["example", "practice", "problem", "exercise", "solution"],
    "material": ["slide", "slides", "lecture", "notes", "audio", "recording", "handout", "reading", "readings", "pdf", "precept"],
    "concept": ["define", "definition", "what is", "what are", "explain", "concept", "concepts", "covered"],
}

INTENT_NODE_TYPE_BOOST = {
    "deadline": {"event": 0.35, "assignment": 0.08, "syllabus": 0.12},
    "exam": {"event": 0.42, "syllabus": 0.15, "file": 0.08, "concept": 0.18},
    "syllabus": {"syllabus": 0.45, "file": 0.22, "event": 0.12},
    "assignment": {"assignment": 0.18, "file": 0.08},
    "practice": {"problem": 0.28, "example": 0.18, "file": 0.1, "concept": 0.08},
    "concept": {"concept": 0.28, "detail": 0.15, "example": 0.12, "file": 0.08},
    "material": {"file": 0.38, "assignment": 0.06},
}

INTENT_NODE_TYPE_PENALTY = {
    "exam": {"assignment": 0.32, "problem": 0.15},
    "deadline": {"problem": 0.12, "example": 0.12},
    "syllabus": {"assignment": 0.28, "problem": 0.15},
}

WEEK_NUMBER_PATTERN = re.compile(r"\bweek\s*(\d+)\b", re.IGNORECASE)
COURSE_CODE_PATTERN = re.compile(
    r"(?<![A-Za-z])"
    r"([A-Za-z]{2,6})"
    r"[\s_-]*"
    r"(\d{2,4}[A-Za-z]?)"
    r"(?![0-9])",
    re.IGNORECASE,
)
COURSE_CODE_STRONG_MATCH = 0.95
COURSE_MATCH_CUTOFF_FUZZY = 0.22
COURSE_MATCH_STRONG_CUTOFF_FUZZY = 0.12
COMBINED_CUTOFF_FUZZY = 0.28

FILE_QUERY_KEYWORDS = [
    "slide",
    "slides",
    "lecture",
    "notes",
    "pdf",
    "reading",
    "readings",
    "audio",
    "recording",
    "handout",
    "syllabus",
]

EXAM_ASSIGNMENT_PATTERN = re.compile(
    r"\b(exam|midterm|final|quiz|test|review)\b",
    re.IGNORECASE,
)

NODE_TYPE_SEARCH_PHRASES = {
    "event": "calendar exam quiz deadline office hours schedule date",
    "syllabus": "syllabus course policy grading schedule class information",
    "file": "lecture slides notes pdf reading handout study material",
    "assignment": "assignment homework problem set submission due",
    "problem": "practice problem exercise solution",
    "concept": "concept definition explanation topic",
}

FUZZY_STOPWORDS = {
    "a",
    "about",
    "an",
    "and",
    "are",
    "as",
    "at",
    "be",
    "by",
    "can",
    "could",
    "course",
    "define",
    "describe",
    "do",
    "does",
    "find",
    "for",
    "from",
    "give",
    "how",
    "in",
    "is",
    "it",
    "me",
    "of",
    "on",
    "or",
    "please",
    "search",
    "should",
    "show",
    "summarize",
    "tell",
    "the",
    "to",
    "what",
    "when",
    "where",
    "who",
    "why",
    "would",
    "with",
}

RETRIEVAL_SEMANTIC_SCORE_CUTOFF = 0.45
BROWSER_INTERNAL_SCORE_CUTOFF = RETRIEVAL_SEMANTIC_SCORE_CUTOFF
BROWSER_RETRIEVAL_CANDIDATES = 12
COURSE_SEMANTIC_FUZZY_STRONG_THRESHOLD = 1.3
COURSE_SEMANTIC_FUZZY_POOL_THRESHOLD = 0.35
GLOBAL_COURSE_BUCKET_KEY = "__global__"

PREFIX_PATTERN = re.compile(
    r"^(?:" + "|".join(re.escape(prefix) for prefix in QUERY_PREFIXES) + r")\s+",
    re.IGNORECASE
)


def sanitize_query(query, max_chars=4000):
    query = str(query or "")
    query = re.sub(r"<[^>]+>", " ", query)
    query = unescape(query)
    query = re.sub(r"\s+", " ", query).strip()
    return query[:max_chars]


def normalize_academic_query(query):
    query = sanitize_query(query)
    query = PREFIX_PATTERN.sub("", query, count=1).strip()
    return query


def normalize_course_code(dept, number):
    return f"{str(dept or '').upper()} {str(number or '').upper()}".strip()


def course_code_variants(dept, number):
    dept_upper = str(dept or "").upper()
    number_upper = str(number or "").upper()
    spaced = normalize_course_code(dept_upper, number_upper)
    compact = f"{dept_upper}{number_upper}"
    return {
        spaced.lower(),
        compact.lower(),
        f"{dept_upper.lower()} {number_upper.lower()}",
    }


def extract_course_codes_from_text(text):
    codes = set()
    for match in COURSE_CODE_PATTERN.finditer(str(text or "")):
        codes.update(course_code_variants(match.group(1), match.group(2)))
    return codes


def extract_course_codes_from_query(query):
    return extract_course_codes_from_text(normalize_academic_query(query))


def course_code_match_score(query, catalog_entry):
    query_codes = extract_course_codes_from_query(query)
    if not query_codes:
        return 0.0
    entry_codes = set(catalog_entry.get("course_codes") or [])
    entry_text = " ".join([
        str(catalog_entry.get("keyword_name") or ""),
        str(catalog_entry.get("name") or ""),
    ]).lower()
    entry_compact = entry_text.replace(" ", "")
    for code in query_codes:
        if code in entry_codes:
            return 1.0
        if code.replace(" ", "") in entry_compact:
            return COURSE_CODE_STRONG_MATCH
    return 0.0


def classify_query_intent(query):
    lowered = sanitize_query(query).lower()
    for intent, keywords in INTENT_KEYWORDS.items():
        if any(keyword in lowered for keyword in keywords):
            return intent
    return "general"


def assignment_exam_like(name):
    return bool(EXAM_ASSIGNMENT_PATTERN.search(str(name or "")))


def node_ranking_text(nodetype, node, courseid=None):
    resolved_courseid = str(courseid or getattr(node, "courseid", "") or "")
    parts = [
        fuzzy_match_name(node, courseid),
        str(getattr(node, "name", "") or ""),
        str(getattr(node, "description", "") or ""),
    ]
    if nodetype == "syllabus" and resolved_courseid:
        catalog_entry = COURSE_CATALOG.get(resolved_courseid, {})
        parts.extend([
            catalog_entry.get("keyword_name", ""),
            catalog_entry.get("name", ""),
            get_course_name(resolved_courseid),
        ])
        parts.extend(catalog_entry.get("course_codes") or [])
    event_type = getattr(node, "type", "")
    if event_type:
        parts.append(str(event_type))
    if getattr(node, "startdate", ""):
        parts.append(str(getattr(node, "startdate", "")))
    if getattr(node, "duedate", ""):
        parts.append(str(getattr(node, "duedate", "")))
    phrase = NODE_TYPE_SEARCH_PHRASES.get(nodetype, "")
    if phrase:
        parts.append(phrase)
    return " ".join(part for part in parts if part)


def intent_type_adjustment(intent, nodetype, node):
    boost = INTENT_NODE_TYPE_BOOST.get(intent, {}).get(nodetype, 0.0)
    penalty = INTENT_NODE_TYPE_PENALTY.get(intent, {}).get(nodetype, 0.0)
    if intent in {"exam", "deadline"} and nodetype == "assignment":
        if assignment_exam_like(getattr(node, "name", "")):
            penalty = 0.0
            boost = max(boost, 0.12)
    if nodetype == "event" and getattr(node, "startdate", ""):
        boost += 0.08
    if nodetype == "event" and str(getattr(node, "type", "") or "").lower() == "office_hours":
        boost += 0.12
    return boost - penalty


def browser_file_query_boost(query, nodetype):
    if nodetype != "file":
        return 0.0
    lowered = sanitize_query(query).lower()
    if any(keyword in lowered for keyword in FILE_QUERY_KEYWORDS):
        return 0.14
    return 0.0


def browser_syllabus_query_boost(query, nodetype):
    if nodetype != "syllabus":
        return 0.0
    lowered = sanitize_query(query).lower()
    if "syllabus" in lowered or "grading" in lowered or "policy" in lowered:
        return 0.2
    return 0.0


def week_query_file_boost(query, nodetype, node):
    if nodetype != "file" or node is None:
        return 0.0
    match = WEEK_NUMBER_PATTERN.search(sanitize_query(query))
    if not match:
        return 0.0
    week_num = match.group(1)
    name = str(getattr(node, "name", "") or "").lower()
    week_markers = (f"week {week_num}", f"week{week_num}", f"w{week_num}", f"_w{week_num}")
    if any(marker in name for marker in week_markers):
        return 0.2
    return 0.0


def browser_allowed_types(mode, intent):
    allowed = {"file", "assignment"}
    if mode == "browser" and intent in {"syllabus", "material"}:
        allowed.add("syllabus")
    return allowed


def passes_retrieval_cutoff(
    semantic_similarity,
    fuzzy_similarity,
    course_similarity,
    intent,
    nodetype,
    node,
    query="",
    mode="agent",
    cutoff_score=RETRIEVAL_SEMANTIC_SCORE_CUTOFF,
):
    if semantic_similarity >= cutoff_score:
        return True
    adjustment = intent_type_adjustment(intent, nodetype, node)
    if mode == "browser":
        adjustment += browser_file_query_boost(query, nodetype)
        adjustment += browser_syllabus_query_boost(query, nodetype)
    if adjustment > 0 and fuzzy_similarity >= 0.45 and (semantic_similarity + adjustment) >= cutoff_score:
        return True
    if course_similarity >= 0.35 and fuzzy_similarity >= COURSE_MATCH_CUTOFF_FUZZY:
        return True
    if course_similarity >= 0.55 and fuzzy_similarity >= COURSE_MATCH_STRONG_CUTOFF_FUZZY:
        return True
    combined = semantic_similarity + fuzzy_similarity + max(0.0, adjustment)
    return combined >= cutoff_score and fuzzy_similarity >= COMBINED_CUTOFF_FUZZY


def prepare_query_for_embedding(query):
    normalized = normalize_academic_query(query)
    if not normalized:
        raise ValueError("Query is empty")

    intent = classify_query_intent(query)
    context = INTENT_CONTEXT.get(intent, INTENT_CONTEXT["general"])
    return {
        "original": sanitize_query(query),
        "normalized": normalized,
        "intent": intent,
        "embedding_text": f"{normalized}. {context}",
    }


def split_fuzzy_keywords(text):
    text = sanitize_query(text, max_chars=1000).lower()
    text = re.sub(r"[\s#.]+", " ", text)
    text = re.sub(r"[^a-z0-9 ]+", " ", text)
    return [
        term
        for term in text.split()
        if len(term) > 2 and term not in FUZZY_STOPWORDS
    ]


def fuzzy_query_terms(query):
    return split_fuzzy_keywords(normalize_academic_query(query))


def keyword_set_similarity(query_terms, name_terms):
    query_set = set(query_terms)
    name_set = set(name_terms)
    if not query_set or not name_set:
        return 0.0

    exact_overlap = query_set & name_set
    exact_coverage = len(exact_overlap) / len(query_set)
    exact_jaccard = len(exact_overlap) / len(query_set | name_set)

    fuzzy_matches = 0
    for query_term in query_set:
        if max(best_partial_ratio(query_term, name_term) for name_term in name_set) >= 0.82:
            fuzzy_matches += 1
    fuzzy_coverage = fuzzy_matches / len(query_set)

    return max(exact_coverage, fuzzy_coverage, exact_jaccard)


def best_partial_ratio(needle, haystack):
    if not needle or not haystack:
        return 0.0
    if needle in haystack:
        return 1.0

    needle_len = len(needle)
    haystack_len = len(haystack)
    if needle_len >= haystack_len:
        return SequenceMatcher(None, needle, haystack).ratio()

    best = 0.0
    for start in range(0, haystack_len - needle_len + 1):
        window = haystack[start:start + needle_len]
        best = max(best, SequenceMatcher(None, needle, window).ratio())
    return best


def fuzzy_name_similarity(query_terms, node_name):
    name_terms = split_fuzzy_keywords(node_name)
    if not query_terms or not name_terms:
        return 0.0

    token_scores = [
        max(best_partial_ratio(term, name_term) for name_term in name_terms)
        for term in query_terms
    ]
    keyword_score = sum(token_scores) / len(token_scores) if token_scores else 0.0
    coverage = sum(1 for score in token_scores if score >= 0.82) / len(query_terms)
    set_score = keyword_set_similarity(query_terms, name_terms)

    return (0.5 * set_score) + (0.35 * keyword_score) + (0.15 * coverage)


def fuzzy_match_name(node, courseid=None):
    name = getattr(node, "name", "")
    scoped_courseid = courseid or getattr(node, "courseid", "")
    return course_scoped_embedding_name(scoped_courseid, name)


def combine_retrieval_scores(embedding_similarity, fuzzy_similarity, course_similarity=0.0):
    return embedding_similarity + fuzzy_similarity + float(course_similarity or 0.0)


def load_course_lookup(path=CANVAS_DATA_PATH):
    if not path.exists():
        return {}
    try:
        with open(path, "r", encoding="utf-8") as file:
            data = json.load(file)
    except (OSError, json.JSONDecodeError):
        return {}

    lookup = {}
    for course in data.get("courses", []) or []:
        courseid = str(course.get("id", "") or "")
        if not courseid:
            continue
        name = str(course.get("name", "") or "").strip()
        code = str(course.get("course_code", "") or "").strip()
        display_name = name or code or f"Canvas {courseid}"
        keyword_name = " ".join(part for part in (name, code) if part)
        lookup[courseid] = {
            "name": display_name,
            "keyword_name": keyword_name or display_name
        }
    return lookup


COURSE_LOOKUP = load_course_lookup()


def get_course_name(courseid):
    item = COURSE_LOOKUP.get(str(courseid or ""))
    if item:
        return item.get("name", "")
    return ""


def course_keyword_similarity(query_terms, courseid, catalog=None):
    item = (catalog or COURSE_CATALOG).get(str(courseid or ""))
    if not item:
        return 0.0
    keyword_name = item.get("keyword_name") or item.get("name") or ""
    return keyword_set_similarity(query_terms, split_fuzzy_keywords(keyword_name))


def vectorize_embedding(value):
    if isinstance(value, list):
        return np.array(value, dtype=np.float32)
    return value


def vectorize_embedded(embedded):
    if not isinstance(embedded, dict):
        return {}
    return {
        key: vectorize_embedding(value)
        for key, value in embedded.items()
    }


def reconstruct_detail(data):
    node = detailNode(
        data.get("name", "No name"),
        data.get("description", "")
    )
    node.courseid = data.get("courseid", "")
    node.embedded = vectorize_embedded(data.get("embedded", {}))
    return node


def reconstruct_example(data):
    node = exampleNode(
        data.get("name", "No name"),
        data.get("description", "")
    )
    node.embedded = vectorize_embedded(data.get("embedded", {}))
    return node


def reconstruct_concept(data):
    node = conceptNode(
        data.get("courseid", "No courseid"),
        data.get("name", "No name"),
        data.get("conceptid"),
        data.get("description", "")
    )
    node.embedded = vectorize_embedded(data.get("embedded", {}))
    node.details = [
        reconstruct_detail(detail)
        for detail in data.get("details", []) or []
    ]
    node.examples = [
        reconstruct_example(example)
        for example in data.get("examples", []) or []
    ]
    node.problems = data.get("problems", []) or []
    return node


def reconstruct_problem(data):
    node = problemNode(
        data.get("name", "No name"),
        data.get("problemid"),
        data.get("incomingConceptNodeIds", []) or [],
        data.get("outgoingConceptNodeIds", []) or [],
        data.get("steps", []) or [],
        data.get("answer", "None"),
        data.get("assignmentNodeIds", []) or []
    )
    node.embedded = vectorize_embedded(data.get("embedded", {}))
    return node


def reconstruct_assignment(data):
    node = assignmentNode(
        data.get("name", "No name"),
        data.get("unlockdate", ""),
        data.get("duedate", ""),
        data.get("gradepercentage", ""),
        data.get("description", ""),
        data.get("problems", []) or [],
        data.get("downloadurl", ""),
        data.get("canvaspreviewurl", "")
    )
    node.assignmentid = data.get("assignmentid", node.assignmentid)
    node.embedded = vectorize_embedded(data.get("embedded", {}))
    return node


def reconstruct_syllabus(data):
    node = syllabusNode(
        data.get("courseid", "No courseid"),
        data.get("classtimes", ""),
        [],
        data.get("other", ""),
        data.get("filechildren", []) or [],
        data.get("downloadurl", ""),
        data.get("canvaspreviewurl", ""),
        data.get("participationgrade")
    )
    node.assignments = [
        reconstruct_assignment(assignment)
        for assignment in data.get("assignments", []) or []
    ]
    for assignment in node.assignments:
        assignment.courseid = node.courseid
    node.embedded = vectorize_embedded(data.get("embedded", {}))
    return node


def reconstruct_file(data):
    node = fileNode(
        data.get("fileid", ""),
        data.get("courseid", "No courseid"),
        data.get("name", ""),
        data.get("downloadurl", ""),
        data.get("canvaspreviewurl", "")
    )
    node.concepts = data.get("concepts", []) or []
    node.details = data.get("details", []) or []
    node.examples = data.get("examples", []) or []
    node.problems = data.get("problems", []) or []
    node.embedded = vectorize_embedded(data.get("embedded", {}))
    return node


def reconstruct_event(data):
    node = eventNode(
        data.get("name", "No name"),
        data.get("startdate", ""),
        data.get("enddate", ""),
        data.get("gradepercentage", ""),
        data.get("description", ""),
        data.get("type", ""),
        data.get("dependencies", []) or []
    )
    node.eventid = data.get("eventid", node.eventid)
    node.courseid = data.get("courseid", "")
    node.coveredConcepts = data.get("coveredConcepts", []) or []
    node.embedded = vectorize_embedded(data.get("embedded", {}))
    return node


def reconstruct_nodes(path=CANVAS_GRAPH_PATH):
    with open(path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    concepts = [reconstruct_concept(item) for item in data.get("concepts", []) or []]
    problems = [reconstruct_problem(item) for item in data.get("problems", []) or []]
    events = [reconstruct_event(item) for item in data.get("events", []) or []]
    syllabi = {
        courseid: reconstruct_syllabus(syllabus)
        for courseid, syllabus in (data.get("syllabi", {}) or {}).items()
    }
    files = {
        courseid: {
            fileid: reconstruct_file(file_data)
            for fileid, file_data in (course_files or {}).items()
        }
        for courseid, course_files in (data.get("files", {}) or {}).items()
    }

    return {
        "concepts": concepts,
        "problems": problems,
        "events": events,
        "syllabi": syllabi,
        "files": files,
        "learningBlocks": data.get("learningBlocks", {}) or {},
        "edges": data.get("edges", []) or [],
        "logged_details": data.get("logged_details", {}),
        "logged_examples": data.get("logged_examples", {}),
        "logged_problems": data.get("logged_problems", {}),
        "logged_assignments": data.get("logged_assignments", {}),
        "logged_events": data.get("logged_events", {}),
    }

allnodes = reconstruct_nodes()
_course_embeddings_cache = None


def build_course_catalog(allnodes_ref=None):
    nodes = allnodes_ref or allnodes
    catalog = {
        str(courseid): dict(info)
        for courseid, info in COURSE_LOOKUP.items()
    }
    for courseid in nodes.get("syllabi", {}):
        cid = str(courseid)
        if cid not in catalog:
            catalog[cid] = {
                "name": f"Canvas {cid}",
                "keyword_name": f"canvas {cid}",
            }
        catalog[cid] = enrich_catalog_entry_from_graph(cid, catalog[cid], nodes)
    return catalog


def enrich_catalog_entry_from_graph(courseid, entry, nodes):
    cid = str(courseid)
    enriched = dict(entry)
    alias_set = set()
    keyword_parts = [enriched.get("name", ""), enriched.get("keyword_name", "")]
    display_name = enriched.get("name", "")

    for filenode in (nodes.get("files", {}) or {}).get(cid, {}).values():
        fname = str(getattr(filenode, "name", "") or "")
        alias_set.update(extract_course_codes_from_text(fname))
        lowered = fname.lower()
        if "homepage" in lowered or "syllabus" in lowered or "general chemistry" in lowered:
            readable = fname.replace("_", " ").rsplit(".", 1)[0].strip()
            keyword_parts.append(readable)
            if len(readable) > len(display_name):
                display_name = readable

    syllabus = (nodes.get("syllabi", {}) or {}).get(cid)
    if syllabus is not None:
        alias_set.update(extract_course_codes_from_text(getattr(syllabus, "other", "")))

    enriched["course_codes"] = sorted(alias_set)
    enriched["name"] = display_name or enriched.get("name", "")
    keyword_parts.extend(alias_set)
    enriched["keyword_name"] = " ".join(
        part for part in dict.fromkeys(part.strip() for part in keyword_parts if part and part.strip())
    )
    return enriched


def build_course_names_list(catalog=None):
    catalog = catalog or build_course_catalog()
    return [
        {
            "courseid": courseid,
            "name": info.get("name", ""),
            "keyword_name": info.get("keyword_name", "") or info.get("name", ""),
        }
        for courseid, info in sorted(catalog.items(), key=lambda item: item[1].get("name", ""))
    ]


def build_course_buckets(allnodes_ref=None):
    nodes = allnodes_ref or allnodes
    buckets = {}

    def add(courseid, nodetype, node):
        cid = str(courseid or "").strip()
        bucket_key = cid if cid else GLOBAL_COURSE_BUCKET_KEY
        buckets.setdefault(bucket_key, []).append((nodetype, node, cid))

    for conceptnode in nodes.get("concepts", []) or []:
        courseid = getattr(conceptnode, "courseid", "")
        add(courseid, "concept", conceptnode)
        for detailnode in conceptnode.details:
            add(courseid, "detail", detailnode)
        for examplenode in conceptnode.examples:
            add(courseid, "example", examplenode)

    for problemnode in nodes.get("problems", []) or []:
        add(getattr(problemnode, "courseid", ""), "problem", problemnode)

    for eventnode in nodes.get("events", []) or []:
        add(getattr(eventnode, "courseid", ""), "event", eventnode)

    for courseid, syllabusnode in (nodes.get("syllabi", {}) or {}).items():
        cid = str(courseid)
        add(cid, "syllabus", syllabusnode)
        for assignmentnode in syllabusnode.assignments:
            add(cid, "assignment", assignmentnode)

    for courseid, coursefiles in (nodes.get("files", {}) or {}).items():
        for filenode in coursefiles.values():
            add(courseid, "file", filenode)

    return buckets


COURSE_CATALOG = build_course_catalog()
COURSE_NAMES_LIST = build_course_names_list(COURSE_CATALOG)
COURSE_BUCKETS = build_course_buckets()


def build_edge_lookup(edges):
    by_from = {}
    for edge in edges or []:
        key = (str(edge.get("fromType") or ""), str(edge.get("fromId") or ""))
        by_from.setdefault(key, []).append(edge)
    return by_from


EDGE_LOOKUP = build_edge_lookup(allnodes.get("edges", []))


def find_file(fileid, courseid=None):
    fileid = str(fileid or "")
    if courseid is not None:
        filenode = allnodes["files"].get(str(courseid), {}).get(fileid)
        if filenode:
            return filenode
    for coursefiles in allnodes["files"].values():
        filenode = coursefiles.get(fileid)
        if filenode:
            return filenode
    return None


def find_event(eventid):
    eventid = str(eventid or "")
    for event in allnodes["events"]:
        if str(getattr(event, "eventid", "")) == eventid:
            return event
    return None


def get_course_embeddings(catalog=None):
    global _course_embeddings_cache
    if _course_embeddings_cache is not None:
        return _course_embeddings_cache

    catalog = catalog or COURSE_CATALOG
    courseids = []
    texts = []
    for courseid, info in catalog.items():
        courseids.append(str(courseid))
        texts.append(info.get("keyword_name") or info.get("name") or str(courseid))

    if not texts:
        _course_embeddings_cache = {}
        return _course_embeddings_cache

    response = openai_client.embeddings.create(
        input=texts,
        model="text-embedding-3-small"
    )
    _course_embeddings_cache = {
        courseid: np.array(item.embedding, dtype=np.float32)
        for courseid, item in zip(courseids, response.data)
    }
    return _course_embeddings_cache


def score_courses_for_query(query, query_terms, embeddedq, catalog=None, course_embeddings=None):
    catalog = catalog or COURSE_CATALOG
    course_embeddings = course_embeddings or get_course_embeddings(catalog)
    scored = []

    for courseid, info in catalog.items():
        keyword_name = info.get("keyword_name") or info.get("name") or ""
        keyword_score = keyword_set_similarity(query_terms, split_fuzzy_keywords(keyword_name))
        fuzzy_score = fuzzy_name_similarity(query_terms, keyword_name)
        course_vector = course_embeddings.get(str(courseid))
        semantic_score = float(np.dot(embeddedq, course_vector)) if course_vector is not None else 0.0
        code_score = course_code_match_score(query, info)
        semantic_fuzzy = semantic_score + fuzzy_score + code_score
        scored.append({
            "courseid": str(courseid),
            "name": info.get("name", ""),
            "keyword_score": max(keyword_score, code_score),
            "fuzzy_score": fuzzy_score,
            "semantic_score": semantic_score,
            "course_code_score": code_score,
            "semantic_fuzzy": semantic_fuzzy,
        })

    scored.sort(
        key=lambda item: (item["course_code_score"], item["keyword_score"], item["semantic_fuzzy"], item["fuzzy_score"]),
        reverse=True
    )
    return scored


def select_course_search_pool(course_scores, query=""):
    code_matches = [
        item for item in course_scores
        if item.get("course_code_score", 0) >= COURSE_CODE_STRONG_MATCH
    ]
    if code_matches:
        return {item["courseid"] for item in code_matches}, "course_code", code_matches

    keyword_matches = [item for item in course_scores if item["keyword_score"] > 0]
    candidates = keyword_matches if keyword_matches else course_scores

    strong_matches = [
        item for item in candidates
        if item["semantic_fuzzy"] >= COURSE_SEMANTIC_FUZZY_STRONG_THRESHOLD
    ]
    if strong_matches:
        return {item["courseid"] for item in strong_matches}, "strong", strong_matches

    moderate_matches = [
        item for item in candidates
        if item["semantic_fuzzy"] >= COURSE_SEMANTIC_FUZZY_POOL_THRESHOLD
    ]
    if moderate_matches:
        top_score = moderate_matches[0]["semantic_fuzzy"]
        if query and extract_course_codes_from_query(query):
            trimmed = [
                item for item in moderate_matches
                if item["semantic_fuzzy"] >= top_score - 0.08
            ]
            if trimmed:
                moderate_matches = trimmed[:4]
        return {item["courseid"] for item in moderate_matches}, "moderate", moderate_matches

    return None, "all", course_scores


def iter_bucket_nodes(course_pool=None):
    if course_pool is None:
        for entries in COURSE_BUCKETS.values():
            yield from entries
        return

    for courseid in course_pool:
        yield from COURSE_BUCKETS.get(str(courseid), [])


def node_identity(nodetype, node):
    return (
        nodetype,
        str(
            getattr(node, "conceptid", None) or
            getattr(node, "problemid", None) or
            getattr(node, "assignmentid", None) or
            getattr(node, "eventid", None) or
            getattr(node, "fileid", None) or
            getattr(node, "courseid", None) or
            getattr(node, "name", "")
        )
    )


def iter_assignments():
    for syllabus in allnodes["syllabi"].values():
        for assignment in syllabus.assignments:
            yield assignment


def find_problem(problemid):
    problemid = str(problemid or "")
    for problem in allnodes["problems"]:
        if str(getattr(problem, "problemid", "")) == problemid:
            return problem
    return None


def find_assignment(assignmentid):
    assignmentid = str(assignmentid or "")
    for assignment in iter_assignments():
        if str(getattr(assignment, "assignmentid", "")) == assignmentid:
            return assignment
    return None


def find_concept(conceptid):
    conceptid = str(conceptid or "")
    for concept in allnodes["concepts"]:
        if str(getattr(concept, "conceptid", "")) == conceptid:
            return concept
    return None


def find_concept_by_name(name, courseid=None):
    name_lower = str(name or "").strip().lower()
    if not name_lower:
        return None
    scoped = str(courseid or "").strip()
    for concept in allnodes["concepts"]:
        if scoped and str(getattr(concept, "courseid", "")) != scoped:
            continue
        if str(getattr(concept, "name", "")).strip().lower() == name_lower:
            return concept
    for concept in allnodes["concepts"]:
        if scoped and str(getattr(concept, "courseid", "")) != scoped:
            continue
        concept_name = str(getattr(concept, "name", "")).strip().lower()
        if name_lower in concept_name or concept_name in name_lower:
            return concept
    return None


def event_concept_neighbors(event):
    neighbors = []
    seen = set()
    courseid = str(getattr(event, "courseid", "") or "")

    def add_concept(concept):
        if concept is None:
            return
        key = str(getattr(concept, "conceptid", "") or getattr(concept, "name", ""))
        if not key or key in seen:
            return
        seen.add(key)
        neighbors.append(("concept", concept))

    for item in getattr(event, "coveredConcepts", []) or []:
        if isinstance(item, dict):
            concept = find_concept(item.get("conceptid"))
            if concept is None and item.get("name"):
                concept = find_concept_by_name(item.get("name"), courseid)
            add_concept(concept)
        elif isinstance(item, str):
            add_concept(find_concept_by_name(item, courseid))

    for dependency in getattr(event, "dependencies", []) or []:
        if isinstance(dependency, str):
            add_concept(find_concept_by_name(dependency, courseid))

    return neighbors


def node_neighbors(nodetype, node):
    neighbors = []
    if nodetype in {"detail", "example"}:
        child_kind = "details" if nodetype == "detail" else "examples"
        ref_kind = "detail" if nodetype == "detail" else "example"
        for concept in allnodes["concepts"]:
            children = getattr(concept, child_kind, []) or []
            if any(child is node for child in children):
                neighbors.append(("concept", concept))
                child_ref = f"{ref_kind}:{getattr(concept, 'conceptid', '')}:{getattr(node, 'name', '')}"
                for coursefiles in allnodes["files"].values():
                    for filenode in coursefiles.values():
                        file_refs = getattr(filenode, child_kind, []) or []
                        if child_ref in file_refs or getattr(node, "name", "") in file_refs:
                            neighbors.append(("file", filenode))
                break
        return neighbors

    if nodetype == "concept":
        for detail in getattr(node, "details", []) or []:
            neighbors.append(("detail", detail))
        for example in getattr(node, "examples", []) or []:
            neighbors.append(("example", example))
        for problemid in getattr(node, "problems", []) or []:
            problem = find_problem(problemid)
            if problem:
                neighbors.append(("problem", problem))
        conceptid = getattr(node, "conceptid", "")
        for coursefiles in allnodes["files"].values():
            for filenode in coursefiles.values():
                if conceptid and conceptid in (getattr(filenode, "concepts", []) or []):
                    neighbors.append(("file", filenode))
        for assignment in iter_assignments():
            assignment_problems = getattr(assignment, "problems", []) or []
            if any(problemid in assignment_problems for problemid in getattr(node, "problems", []) or []):
                neighbors.append(("assignment", assignment))
        conceptid = getattr(node, "conceptid", "")
        for prereq_id in getattr(node, "prerequisiteConceptIds", []) or []:
            prereq = find_concept(prereq_id)
            if prereq:
                neighbors.append(("concept", prereq))
        for other in allnodes["concepts"]:
            if conceptid and conceptid in (getattr(other, "prerequisiteConceptIds", []) or []):
                neighbors.append(("concept", other))
        for blocks in (allnodes.get("learningBlocks", {}) or {}).values():
            for block in blocks or []:
                if str(block.get("conceptId", "")) == str(conceptid):
                    neighbors.append(("learningBlock", block))
        return neighbors

    if nodetype == "problem":
        for conceptid in (getattr(node, "incomingConceptNodeIds", []) or []) + (getattr(node, "outgoingConceptNodeIds", []) or []):
            concept = find_concept(conceptid)
            if concept:
                neighbors.append(("concept", concept))
        for assignmentid in getattr(node, "assignmentNodeIds", []) or []:
            assignment = find_assignment(assignmentid)
            if assignment:
                neighbors.append(("assignment", assignment))
        problemid = getattr(node, "problemid", "")
        for coursefiles in allnodes["files"].values():
            for filenode in coursefiles.values():
                if problemid and problemid in (getattr(filenode, "problems", []) or []):
                    neighbors.append(("file", filenode))
        for assignment in iter_assignments():
            if problemid and problemid in (getattr(assignment, "problems", []) or []):
                neighbors.append(("assignment", assignment))
        return neighbors

    if nodetype == "assignment":
        for problemid in getattr(node, "problems", []) or []:
            problem = find_problem(problemid)
            if problem:
                neighbors.append(("problem", problem))
        return neighbors

    if nodetype == "file":
        for conceptid in getattr(node, "concepts", []) or []:
            concept = find_concept(conceptid)
            if concept:
                neighbors.append(("concept", concept))
        for problemid in getattr(node, "problems", []) or []:
            problem = find_problem(problemid)
            if problem:
                neighbors.append(("problem", problem))
        return neighbors

    if nodetype == "event":
        eventid = str(getattr(node, "eventid", "") or "")
        courseid = str(getattr(node, "courseid", "") or "")
        for edge in EDGE_LOOKUP.get(("event", eventid), []):
            target_type = str(edge.get("toType") or "")
            target_id = str(edge.get("toId") or "")
            if target_type == "file":
                filenode = find_file(target_id, courseid)
                if filenode:
                    neighbors.append(("file", filenode))
            elif target_type == "concept":
                concept = find_concept(target_id)
                if concept:
                    neighbors.append(("concept", concept))
        neighbors.extend(event_concept_neighbors(node))
        syllabus = allnodes["syllabi"].get(courseid)
        if syllabus:
            neighbors.append(("syllabus", syllabus))
        return neighbors

    if nodetype == "syllabus":
        courseid = str(getattr(node, "courseid", "") or "")
        for assignment in getattr(node, "assignments", []) or []:
            neighbors.append(("assignment", assignment))
        for fileid in getattr(node, "filechildren", []) or []:
            filenode = find_file(fileid, courseid)
            if filenode:
                neighbors.append(("file", filenode))
        return neighbors

    return neighbors


def add_result(results, seen, nodetype, node, similarity, source=None, score_parts=None):
    key = node_identity(nodetype, node)
    existing_index = seen.get(key)
    item = {
        'type': nodetype,
        'node': node,
        'similarity': float(similarity),
        'source': source
    }
    if isinstance(score_parts, dict):
        item.update(score_parts)
    if existing_index is None:
        seen[key] = len(results)
        results.append(item)
        return
    if similarity > results[existing_index].get('similarity', 0):
        results[existing_index] = item


def source_context(nodetype, node):
    return {
        "type": nodetype,
        "id": node_identity(nodetype, node)[1],
        "name": getattr(node, "name", ""),
        "description": getattr(node, "description", "")
    }


def expand_startpoints(startpoints, mode, intent="general"):
    if mode == "raw":
        return startpoints

    results = []
    seen = {}
    allowed_browser_types = browser_allowed_types(mode, intent)
    for startpoint in startpoints:
        nodetype = startpoint["type"]
        node = startpoint["node"]
        similarity = startpoint.get("similarity", 0.0)
        score_parts = {
            key: startpoint.get(key)
            for key in ("semantic_similarity", "fuzzy_similarity", "course_similarity")
            if startpoint.get(key) is not None
        }
        if mode == "browser":
            if nodetype in allowed_browser_types:
                add_result(results, seen, nodetype, node, similarity, score_parts=score_parts)
            for neighbor_type, neighbor in node_neighbors(nodetype, node):
                if neighbor_type in allowed_browser_types:
                    add_result(
                        results,
                        seen,
                        neighbor_type,
                        neighbor,
                        similarity,
                        source=source_context(nodetype, node),
                        score_parts=score_parts
                    )
            continue

        add_result(results, seen, nodetype, node, similarity, score_parts=score_parts)
        for neighbor_type, neighbor in node_neighbors(nodetype, node):
            add_result(
                results,
                seen,
                neighbor_type,
                neighbor,
                similarity,
                source=source_context(nodetype, node),
                score_parts=score_parts
            )

    return sorted(results, key=lambda item: item.get("similarity", 0), reverse=True)


def retreive(query, k = 3, mode = "agent"):

    startpoints = []
    heap = []
    heap_counter = 0
    
    newquery = prepare_query_for_embedding(query)
    qv = openai_client.embeddings.create(
        input=newquery["embedding_text"],
        model="text-embedding-3-small"
    )
    embeddedq = np.array(qv.data[0].embedding, dtype=np.float32)
    query_terms = fuzzy_query_terms(query)
    course_embeddings = get_course_embeddings()
    course_scores = score_courses_for_query(query, query_terms, embeddedq, course_embeddings=course_embeddings)
    course_pool, pool_mode, matched_courses = select_course_search_pool(course_scores, query=query)
    course_score_by_id = {item["courseid"]: item for item in course_scores}

    print(
        "Course pool: "
        f"mode={pool_mode}, "
        f"courses={sorted(course_pool) if course_pool else 'all'}, "
        f"top={[item['name'] for item in matched_courses[:3]]}",
        file=sys.stderr
    )

    def push_node(overall_similarity, semantic_similarity, fuzzy_similarity, course_similarity, nodetype, node):
        nonlocal heap_counter
        if overall_similarity > 0:
            heapq.heappush(heap, (
                -float(overall_similarity),
                heap_counter,
                nodetype,
                node,
                float(semantic_similarity),
                float(fuzzy_similarity),
                float(course_similarity)
            ))
            heap_counter += 1

    def passes_semantic_cutoff(semantic_similarity, fuzzy_similarity, course_similarity, nodetype, node):
        return passes_retrieval_cutoff(
            semantic_similarity,
            fuzzy_similarity,
            course_similarity,
            newquery["intent"],
            nodetype,
            node,
            query=query,
            mode=mode,
            cutoff_score=cutoff_score,
        )

    def rank_node(nodetype, node, courseid=None):
        embedded = getattr(node, "embedded", None) or {}
        name_similarity = 0.0
        description_similarity = 0.0
        if embedded:
            if "name" in embedded:
                name_similarity = float(np.dot(embeddedq, embedded.get("name", [])))
            if "description" in embedded:
                description_similarity = float(np.dot(embeddedq, embedded.get("description", [])))
        embedding_similarity = max(name_similarity, description_similarity)
        ranking_text = node_ranking_text(nodetype, node, courseid)
        fuzzy_similarity = fuzzy_name_similarity(query_terms, ranking_text)
        resolved_courseid = str(courseid or getattr(node, "courseid", "") or "")
        course_match = course_score_by_id.get(resolved_courseid, {})
        course_similarity = course_match.get("semantic_fuzzy", 0.0)
        adjustment = intent_type_adjustment(newquery["intent"], nodetype, node)
        if mode == "browser":
            adjustment += browser_file_query_boost(query, nodetype)
            adjustment += browser_syllabus_query_boost(query, nodetype)
            adjustment += week_query_file_boost(query, nodetype, node)
        elif nodetype == "file":
            adjustment += week_query_file_boost(query, nodetype, node)
        overall_similarity = (
            combine_retrieval_scores(embedding_similarity, fuzzy_similarity, course_similarity)
            + adjustment
        )
        push_node(overall_similarity, embedding_similarity, fuzzy_similarity, course_similarity, nodetype, node)

    for nodetype, node, courseid in iter_bucket_nodes(course_pool):
        rank_node(nodetype, node, courseid)

    candidate_count = BROWSER_RETRIEVAL_CANDIDATES if mode == "browser" else k
    cutoff_score = BROWSER_INTERNAL_SCORE_CUTOFF
    while heap and len(startpoints) < candidate_count:
        similarity, _, nodetype, node, semantic_score, fuzzy_score, course_score = heapq.heappop(heap)
        score = -similarity
        print(
            f"Type: {nodetype}, Name: {getattr(node, 'name', 'N/A')}, "
            f"Similarity: {score:.4f}, Semantic: {semantic_score:.4f}, "
            f"Fuzzy: {fuzzy_score:.4f}, Course: {course_score:.4f}",
            file=sys.stderr
        )
        if passes_semantic_cutoff(semantic_score, fuzzy_score, course_score, nodetype, node):
            startpoints.append({
                'type': nodetype,
                'node': node,
                'similarity': score,
                'semantic_similarity': semantic_score,
                'fuzzy_similarity': fuzzy_score,
                'course_similarity': course_score
            })
    return expand_startpoints(startpoints, mode, intent=newquery["intent"])

def serialize_startpoint(startpoint):
    node = startpoint["node"]
    downloadurl = getattr(node, "downloadurl", "") or ""
    canvaspreviewurl = getattr(node, "canvaspreviewurl", "") or ""
    courseid = getattr(node, "courseid", "")
    coursename = get_course_name(courseid)
    return {
        "type": startpoint["type"],
        "name": getattr(node, "name", ""),
        "description": getattr(node, "description", ""),
        "courseid": courseid,
        "coursename": coursename,
        "downloadurl": downloadurl,
        "canvaspreviewurl": canvaspreviewurl,
        "url": canvaspreviewurl or downloadurl,
        "duedate": getattr(node, "duedate", ""),
        "unlockdate": getattr(node, "unlockdate", ""),
        "gradepercentage": getattr(node, "gradepercentage", ""),
        "similarity": startpoint.get("similarity", None),
        "semantic_similarity": startpoint.get("semantic_similarity", None),
        "fuzzy_similarity": startpoint.get("fuzzy_similarity", None),
        "course_similarity": startpoint.get("course_similarity", None),
        "source": startpoint.get("source", None),
        "id": (
            getattr(node, "conceptid", None) or
            getattr(node, "problemid", None) or
            getattr(node, "assignmentid", None) or
            getattr(node, "eventid", None) or
            getattr(node, "fileid", None) or
            getattr(node, "courseid", "")
        )
    }

def print_retrieval_results(results):
    for result in results:
        nodetype = result['type']
        node = result['node']
        print(f"Type: {nodetype}, Name: {getattr(node, 'name', 'N/A')}, description: {getattr(node, 'description', 'N/A')[:100]}...")


def run_service():
    for rawline in sys.stdin:
        rawline = rawline.strip()
        if not rawline:
            continue
        try:
            payload = json.loads(rawline)
            query = payload[1] if isinstance(payload, list) and len(payload) > 1 else payload.get("query", "")
            if isinstance(payload, list):
                mode = payload[2].get("mode", "agent") if len(payload) > 2 and isinstance(payload[2], dict) else "agent"
            else:
                mode = payload.get("mode", "agent")
            print(f"vector retrieval received query: {query}", file=sys.stderr, flush=True)
            startpoints = retreive(query, mode=mode)
            print(json.dumps({
                "query": query,
                "startpoints": [serialize_startpoint(startpoint) for startpoint in startpoints]
            }, ensure_ascii=False), flush=True)
        except Exception as error:
            print(json.dumps({
                "error": str(error),
                "raw": rawline
            }, ensure_ascii=False), flush=True)


if __name__ == "__main__":
    run_service()
    
